#ifndef _MENCI_DEFINES_H
#define _MENCI_DEFINES_H

#define _FP_ENCODING_LENGTH_SIGN     1
#define _FP_ENCODING_LENGTH_EXPONENT 11
#define _FP_ENCODING_LENGTH_FRACTION 52

#define _FP_BIAS (int64_t)((1ULL << (_FP_ENCODING_LENGTH_EXPONENT - 1)) - 1)

#define _FP_EXPONENT_MAX     ((int64_t)(1ULL << _FP_ENCODING_LENGTH_EXPONENT) - 1 - 1)
#define _FP_EXPONENT_ALL_ONE ((int64_t)(1ULL << _FP_ENCODING_LENGTH_EXPONENT) - 1)

#define _FP_OUTPUT_EXPONENT_MAX (_FP_EXPONENT_MAX - _FP_BIAS)
#define _FP_OUTPUT_EXPONENT_MIN (1 - _FP_BIAS - _FP_ENCODING_LENGTH_FRACTION)

#define _FP_BIGNUM_LENGTH (-_FP_OUTPUT_EXPONENT_MIN + 1)

#endif // _MENCI_DEFINES_H
