data : data.c
	gcc data.c -o data
comp : main_comp.c RBTree.c RBTree.h
	gcc main_comp.c RBTree.c -o comp
deco : main_deco.c RBTree.c RBTree.h
	gcc main_deco.c RBTree.c -o deco
clean :
	rm comp deco data 
